import React from "react";
import Head from "next/head";
import Nav from "./nav";
import Footer from "./footer";
import { motion } from "framer-motion";

interface LayoutProps {
  children: React.ReactNode;
}

export default function layout({ children }: LayoutProps) {
  return (
    <div className="bg-primary text-tertiary">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      {children}
      {/* <motion.div
        initial={{ y: 10, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        transition={{
          duration: 0.8,
          delay: 0.1,
        }}
      >
        {children}
      </motion.div> */}
      <Footer />
    </div>
  );
}
